{"name": "Безуспешное вычисление остатка от деления с числом, превышающим размер", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerError\nstatusMessage\n  Field required [type=missing, input_value={'statusCode': 0, 'result': 0}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.8/v/missing", "trace": "self = <tests.calculator_api.test_remainder.TestRemainder object at 0x00000276A4353A70>\ncalculator_steps = <steps.calculator_api.calculator_steps.CalculatorSteps object at 0x00000276A5480C20>, operands = IntegerOperands(x=2147483648, y=-1)\n\n    @allure.title('Безуспешное вычисление остатка от деления с числом, превышающим размер')\n    @pytest.mark.parametrize(\"operands\",\n                             CalculatorDataProvider.get_unsuccessful_oversize_data(),\n                             ids=idfn)\n    def test_unsuccessful_remainder_oversize_number(self, calculator_steps, operands: AnyOperands):\n        response = calculator_steps.do_remainder(operands)\n    \n        # assert_http_status_code(response=response, expected_code=422)\n        assert_json_header(response=response)\n    \n>       error = ServerSchemasSteps.get_server_error(response)\n\ntests\\calculator_api\\test_remainder.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'steps.server_api.server_schemas_steps.ServerSchemasSteps'>, response = <Response [200 OK]>\n\n    @classmethod\n    @allure.step('Получить ошибку сервера из ответа')\n    def get_server_error(cls, response: Response) -> ServerError:\n>       return ServerError.model_validate(response.json())\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerError\nE       statusMessage\nE         Field required [type=missing, input_value={'statusCode': 0, 'result': 0}, input_type=dict]\nE           For further information visit https://errors.pydantic.dev/2.8/v/missing\n\nsteps\\server_api\\server_schemas_steps.py:49: ValidationError"}, "steps": [{"name": "Посчитать остаток от деления чисел", "status": "passed", "steps": [{"name": "Остаток от деления x на y", "status": "passed", "steps": [{"name": "Отправка \"'POST'\" запроса на \"'/remainder'\"", "status": "passed", "parameters": [{"name": "method", "value": "'POST'"}, {"name": "url", "value": "'/remainder'"}, {"name": "content", "value": "None"}, {"name": "data", "value": "None"}, {"name": "files", "value": "None"}, {"name": "json", "value": "{'x': 2147483648, 'y': -1}"}, {"name": "params", "value": "None"}, {"name": "headers", "value": "None"}, {"name": "cookies", "value": "None"}, {"name": "auth", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "follow_redirects", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "timeout", "value": "<httpx._client.UseClientDefault object at 0x00000276A3624C20>"}, {"name": "extensions", "value": "None"}], "start": 1723569766008, "stop": 1723569766024}], "parameters": [{"name": "operands_payload", "value": "{'x': 2147483648, 'y': -1}"}], "start": 1723569766008, "stop": 1723569766024}], "parameters": [{"name": "operands", "value": "IntegerOperands(x=2147483648, y=-1)"}], "start": 1723569766008, "stop": 1723569766024}, {"name": "Получить ошибку сервера из ответа", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerError\nstatusMessage\n  Field required [type=missing, input_value={'statusCode': 0, 'result': 0}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.8/v/missing\n", "trace": "  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\steps\\server_api\\server_schemas_steps.py\", line 49, in get_server_error\n    return ServerError.model_validate(response.json())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Проекты прогерские\\Проекты PyCharm\\api_testing\\venv\\Lib\\site-packages\\pydantic\\main.py\", line 568, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [200 OK]>"}], "start": 1723569766024, "stop": 1723569766024}], "parameters": [{"name": "operands", "value": "IntegerOperands(x=2147483648, y=-1)"}], "start": 1723569766008, "stop": 1723569766024, "uuid": "d99cdbf6-da95-46ff-b8c7-5f2765d8ce5d", "historyId": "ced91e697dee07daae0bfdefdc3c0384", "testCaseId": "8d8a5b036124d2e67c375323e91f87b5", "fullName": "tests.calculator_api.test_remainder.TestRemainder#test_unsuccessful_remainder_oversize_number", "labels": [{"name": "story", "value": "Вычисление остатка от деления"}, {"name": "epic", "value": "Калькулятор"}, {"name": "feature", "value": "Вычисления калькулятора"}, {"name": "parentSuite", "value": "tests.calculator_api"}, {"name": "suite", "value": "test_remainder"}, {"name": "subSuite", "value": "TestRemainder"}, {"name": "host", "value": "DESKTOP-QQNQKOJ"}, {"name": "thread", "value": "11904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.calculator_api.test_remainder"}]}